language: python
python:
  - '2.7'
  - '3.4'
env:
  - DJANGO=1.5.12 DB=postgres
  - DJANGO=1.6.11 DB=postgres
  - DJANGO=1.7.7 DB=postgres
install:
  - pip install -q coverage flake8 Django==$DJANGO
before_script:
  - psql -c 'CREATE DATABASE regex_field;' -U postgres
script:
  - flake8 .
  - coverage run setup.py test
  - coverage report --fail-under=100
